<<<<<<< HEAD
resources:
  - name: hello-repo
    type: git
    source:
      uri: https://github.com/amitopenwriteup/concourse.git
      branch: main

jobs:
  - name: hello-world-job
    public: true
    plan:
      - get: hello-repo
        trigger: true

      - task: print-hello
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: alpine
              tag: latest
          inputs:
            - name: hello-repo
          run:
            path: sh
            args:
              - -exc
              - |
                echo " Running Hello World Task"
                echo "Contents of hello-repo directory:"
                ls -al hello-repo
                echo "Hello from Concourse Pipeline!"
=======
resource_types:
- name: registry-image
  type: registry-image
  source:
    repository: concourse/registry-image-resource

jobs:
- name: hello-world
  plan:
  - task: say-hello
    config:
      platform: linux
      image_resource:
        source: { repository: alpine }
      run:
        path: echo
        args: ["Hello, world!"]
>>>>>>> 94bffb3 (add)
