resources:
  - name: hello-repo
    type: git
    source:
      uri: https://github.com/amitopenwriteup/concourse.git
      branch: main

jobs:
  - name: hello-world-job
    public: true
    plan:
      - get: hello-repo
        trigger: true

      - task: print-hello
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: alpine
              tag: latest
          inputs:
            - name: hello-repo
          run:
            path: sh
            args:
              - -exc
              - |
                echo " Running Hello World1 Task"
                echo "Contents of hello-repo directory:"
                ls -al hello-repo
                echo "Hello from Concourse Pipeline!"
