jobs:
- name: test-job
  plan:
  - task: show-secret
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      params:
        MY_SECRET: ((secret/concourse/main/demo/my-secret))
      run:
        path: sh
        args:
        - -exc
        - |
          echo "The secret from Vault is: $MY_SECRET"

