---
resources:
- name: every-30s
  type: time
  icon: clock-outline
  source:
    interval: 30s

resources:
- name: scripts
  type: git
  source:
    uri: https://github.com/amitopenwriteup/concourse.git
    branch: main

jobs:
- name: job
  public: true
  build_log_retention:
    builds: 50
  plan:
  - get: every-30s
    trigger: true
  - task: simple-task
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: { repository: busybox }
      inputs:
      - name: scripts
      run:
        path: sh
        args:
          - scripts/hello.sh

